<?php
/*define("SERVIDOR",'24.1daw.esvirgua.com');
define("USUARIO",'user1daw_24');
define("PASSWORD",'Ux{B?iu7~eU5Qs]T');
define("BBDD",'user1daw_BD1-24');*/
define("SERVIDOR",'localhost');
define("USUARIO",'root');
define("PASSWORD",'');
define("BBDD",'jesuitas2026');
?>